version: "2"
services:
  baidupcs-web:
    container_name: baidupcs-web
    image: taketrace00/baidupcs-go-web:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /path/to/config:/config
      - /path/to/downloadsFolder:/root/Downloads
    ports:
      - 5299:5299
    restart: unless-stopped
